name       : astromenace
version    : 1.4.2
release    : 13
source     :
    - https://github.com/viewizard/astromenace/archive/v1.4.2.tar.gz : 616622cc1da07a7d827c0fb94b90b7c9a36a1e7d1e68002ed3aaf2a12b9a99aa
homepage   : https://viewizard.com/
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
    - OFL-1.1
component  : games.action
summary    : Hardcore 3D space scroll-shooter with spaceship upgrade possibilities
description: |
    AstroMenace is an astonishing hardcore scroll-shooter where brave space warriors may find a great opportunity to hone their combat skills.
builddeps  :
    - pkgconfig(freealut)
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    install -Dm00755 astromenace $installdir/usr/bin/astromenace
    install -Dm00644 share/astromenace_128.png $installdir/usr/share/pixmaps/astromenace.png
    install -Dm00644 $pkgfiles/astromenace.desktop $installdir/usr/share/applications/astromenace.desktop
    install -Dm00644 gamedata.vfs $installdir/usr/share/astromenace/gamedata.vfs
