name       : astromenace
version    : 1.4.0
release    : 4
source     :
    - https://github.com/viewizard/astromenace/archive/v1.4.0.tar.gz : 6ebbb14d7b2e066a4f35b104185562560614e125498a63631402fbc77d899f35
license    :
    - CC-BY-SA-3.0
    - GPL-3.0
    - OFL-1.1
component  : games.action
summary    : AstroMenace is an astonishing hardcore scroll-shooter where brave space warriors may find a great opportunity to hone their combat skills.
description: |
    AstroMenace is an astonishing hardcore scroll-shooter where brave space warriors may find a great opportunity to hone their combat skills.
builddeps  :
    - pkgconfig(freealut)
    - pkgconfig(freetype2)
    - pkgconfig(glu)
    - pkgconfig(openal)
    - pkgconfig(sdl2)
    - pkgconfig(vorbis)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    install -D -m 00755 astromenace $installdir/usr/bin/astromenace
    install -D -m 00644 share/astromenace_128.png $installdir/usr/share/pixmaps/astromenace.png

    install -D -m 00644 $pkgfiles/astromenace.desktop $installdir/usr/share/applications/astromenace.desktop

    install -D -m 00644 gamedata.vfs $installdir/usr/share/astromenace/gamedata.vfs
